# Generated by Django 5.0.4 on 2024-04-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=20)),
                ('incorrect_answers', models.TextField()),
            ],
        ),
    ]
