# Generated by Django 5.0.4 on 2024-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='api',
            name='difficulty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='api',
            name='incorrect_answers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
